# Generated by Django 5.2.14 on 2026-05-14 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_doctor_phone_doctor_qualification'),
        ('clinic', '0003_doctor_phone'),
    ]

    operations = [
    ]
